-- Phase 3 test-only authentication slice layered onto the Phase 2 schema fixture.
-- This is not a Flyway baseline and never represents production data.

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(128) NOT NULL UNIQUE,
    password_hash text NOT NULL,
    is_admin boolean NOT NULL DEFAULT false,
    is_locked boolean NOT NULL DEFAULT false,
    session_version integer NOT NULL DEFAULT 0,
    is_subject_admin boolean NOT NULL DEFAULT false,
    is_notification_admin boolean NOT NULL DEFAULT false,
    has_password_set boolean NOT NULL DEFAULT false,
    email text,
    phone varchar(20) UNIQUE,
    openid text,
    last_active timestamp without time zone
);

CREATE INDEX users_email_idx ON users (email);

CREATE TABLE system_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key text NOT NULL UNIQUE,
    config_value text NOT NULL
);
