-- Phase 4B test-only schema for the HTTP-neutral personal-bank category list.
-- This is neither a Flyway baseline nor a production migration.

CREATE TABLE user_bank_categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name text NOT NULL,
    description text,
    sort_order integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT uq_user_bank_categories_user_name UNIQUE (user_id, name)
);

CREATE TABLE user_question_banks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_id integer REFERENCES user_bank_categories(id) ON DELETE SET NULL,
    name text NOT NULL,
    description text,
    cover_image text,
    is_public boolean DEFAULT false,
    public_description text,
    allow_copy boolean DEFAULT true,
    public_at timestamp without time zone,
    question_count integer DEFAULT 0,
    share_count integer DEFAULT 0,
    public_use_count integer DEFAULT 0,
    status integer DEFAULT 1,
    plaza_board_id integer,
    is_plaza_featured boolean DEFAULT false,
    plaza_featured_weight integer DEFAULT 0,
    plaza_featured_at timestamp without time zone,
    join_mode text DEFAULT 'free',
    join_note text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
