-- Phase 4B test-only schema for preimplementation personal-bank share-list evidence.
-- This is neither a Flyway baseline nor a production migration.

CREATE TABLE user_question_banks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_id integer,
    name text NOT NULL,
    description text,
    cover_image text,
    is_public boolean DEFAULT false,
    public_description text,
    allow_copy boolean DEFAULT true,
    public_at timestamp without time zone,
    question_count integer DEFAULT 0,
    share_count integer DEFAULT 0,
    public_use_count integer DEFAULT 0,
    status integer DEFAULT 1,
    plaza_board_id integer,
    is_plaza_featured boolean DEFAULT false,
    plaza_featured_weight integer DEFAULT 0,
    plaza_featured_at timestamp without time zone,
    join_mode text DEFAULT 'free',
    join_note text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE bank_shares (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id integer NOT NULL REFERENCES user_question_banks(id) ON DELETE CASCADE,
    owner_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    share_code text UNIQUE,
    share_token text UNIQUE,
    permission text DEFAULT 'read',
    expires_at timestamp without time zone,
    max_uses integer,
    current_uses integer DEFAULT 0,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now()
);

-- Deliberately no bank_id or created_at index: the legacy schema has neither.
