-- Phase 4B test-only schema for preimplementation personal-bank usage-statistics evidence.
-- This is neither a Flyway baseline nor a production migration.

CREATE TABLE bank_share_records (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_id integer NOT NULL REFERENCES bank_shares(id) ON DELETE CASCADE,
    bank_id integer NOT NULL REFERENCES user_question_banks(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status integer DEFAULT 1,
    last_access_at timestamp without time zone,
    access_count integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    UNIQUE (share_id, user_id)
);

CREATE TABLE public_bank_users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id integer NOT NULL REFERENCES user_question_banks(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    last_access_at timestamp without time zone,
    access_count integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    UNIQUE (bank_id, user_id)
);

-- No extra index is added: legacy UNIQUE (bank_id, user_id) gives
-- public_bank_users a bank_id-leading composite index, while
-- bank_share_records has no bank_id-leading index.
