-- Phase 4B test-only schema for preimplementation personal-bank user-counts evidence.
-- This is neither a Flyway baseline nor a production schema/index authorization.

CREATE TABLE user_bank_questions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id integer NOT NULL REFERENCES user_question_banks(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- Deliberately nullable in this permissive evidence fixture so JDBC raw-type
    -- compatibility is measured before the legacy application drops null values.
    type text,
    content text NOT NULL,
    options text DEFAULT '[]',
    answer text DEFAULT '[]',
    created_at timestamp without time zone DEFAULT now()
);

CREATE INDEX ix_user_bank_questions_bank_id
    ON user_bank_questions (bank_id);

CREATE TABLE user_bank_favorites (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bank_id integer NOT NULL REFERENCES user_question_banks(id) ON DELETE CASCADE,
    question_id integer NOT NULL REFERENCES user_bank_questions(id) ON DELETE CASCADE,
    created_at timestamp without time zone DEFAULT now(),
    UNIQUE (user_id, question_id)
);

CREATE INDEX ix_user_bank_favorites_user_bank
    ON user_bank_favorites (user_id, bank_id);

CREATE TABLE user_bank_mistakes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bank_id integer NOT NULL REFERENCES user_question_banks(id) ON DELETE CASCADE,
    question_id integer NOT NULL REFERENCES user_bank_questions(id) ON DELETE CASCADE,
    wrong_count integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    UNIQUE (user_id, question_id)
);

CREATE INDEX ix_user_bank_mistakes_user_bank
    ON user_bank_mistakes (user_id, bank_id);

CREATE TABLE user_progress (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    p_key text NOT NULL,
    data text NOT NULL,
    updated_at timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now(),
    UNIQUE (user_id, p_key)
);

CREATE TABLE user_question_tag_items (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scope text NOT NULL,
    scope_id integer NOT NULL DEFAULT 0,
    question_id integer NOT NULL,
    tag text NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    PRIMARY KEY (user_id, scope, scope_id, question_id, tag)
);

-- Intentionally absent: the legacy runtime-created tag indexes
-- idx_uqti_user_scope_scopeid_tag and idx_uqti_user_scope_scopeid_qid.
-- Their creation/migration path is outside this read-only SQL evidence gate.
