-- Phase 4C test-only schema for the transaction-write HTTP target execution.
-- This is neither a production Flyway baseline nor authorization to mutate production.

CREATE TABLE favorites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    question_id integer NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_phase4c_http_favorites_user_question
        UNIQUE (user_id, question_id)
);

CREATE TABLE mistakes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    question_id integer NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    wrong_count integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_phase4c_http_mistakes_user_question
        UNIQUE (user_id, question_id)
);

CREATE TABLE user_answers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    question_id integer NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    user_answer text,
    is_correct boolean,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_quiz_stats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    total_answered integer DEFAULT 0,
    last_reset_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE study_learning (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source text NOT NULL,
    scope_id integer NOT NULL,
    question_id bigint NOT NULL,
    streak integer DEFAULT 0,
    is_learned boolean DEFAULT false,
    correct_count integer DEFAULT 0,
    wrong_count integer DEFAULT 0,
    last_result text,
    last_answered_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_phase4c_http_study_learning_scope
        UNIQUE (user_id, source, scope_id, question_id)
);

CREATE TABLE study_review (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source text NOT NULL,
    scope_id integer NOT NULL,
    question_id bigint NOT NULL,
    review_level integer DEFAULT 0,
    next_due_at timestamp without time zone,
    last_review_at timestamp without time zone,
    last_rating text,
    lapse_count integer DEFAULT 0,
    is_mastered boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_phase4c_http_study_review_scope
        UNIQUE (user_id, source, scope_id, question_id)
);

CREATE TABLE user_checkins (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    checkin_date text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_phase4c_http_checkin_day UNIQUE (user_id, checkin_date)
);

CREATE TABLE identity_write_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    changed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    old_row jsonb NOT NULL,
    new_row jsonb NOT NULL
);

CREATE FUNCTION phase4c_http_audit_identity_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO identity_write_audit (user_id, old_row, new_row)
    VALUES (OLD.id, to_jsonb(OLD), to_jsonb(NEW));
    RETURN NEW;
END;
$$;

CREATE TRIGGER phase4c_http_users_update_audit
AFTER UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION phase4c_http_audit_identity_update();
