-- Phase 4A test-only overlay for protected subject-directory reads.
-- This is neither a Flyway baseline nor a production migration.

CREATE TABLE questions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id integer REFERENCES subjects(id) ON DELETE SET NULL,
    type text NOT NULL,
    content text NOT NULL,
    options text DEFAULT '[]',
    answer text DEFAULT '[]',
    analysis text,
    tags text DEFAULT '[]',
    difficulty integer DEFAULT 1,
    image_path text,
    source text,
    created_by integer,
    updated_by integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);

CREATE INDEX ix_questions_subject_id ON questions (subject_id);
CREATE INDEX ix_questions_subject_type ON questions (subject_id, type);

CREATE TABLE user_subjects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject_id integer NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    restricted_at timestamp without time zone DEFAULT now(),
    restricted_by bigint REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT uq_user_subjects_user_subject UNIQUE (user_id, subject_id)
);

CREATE INDEX ix_user_subjects_user_id ON user_subjects (user_id);
