-- Phase 4A test-only complete public-bank catalog snapshot overlay.
-- This is neither a Flyway baseline nor a production migration.

ALTER TABLE plaza_boards
    ADD COLUMN slug text,
    ADD COLUMN name text,
    ADD COLUMN description text,
    ADD COLUMN icon text,
    ADD COLUMN sort_order integer NOT NULL DEFAULT 0,
    ADD COLUMN is_active boolean NOT NULL DEFAULT true,
    ADD COLUMN created_at timestamp without time zone DEFAULT now(),
    ADD COLUMN updated_at timestamp without time zone DEFAULT now();

CREATE UNIQUE INDEX uq_plaza_boards_slug ON plaza_boards (slug);

CREATE TABLE public_bank_plaza_metrics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type text NOT NULL CHECK (source_type IN ('system', 'user_public')),
    source_id bigint NOT NULL,
    name text NOT NULL,
    description text,
    cover_image text,
    owner_id bigint,
    owner_label text NOT NULL,
    owner_avatar text,
    question_count_total bigint NOT NULL DEFAULT 0,
    plaza_board_id integer REFERENCES plaza_boards(id) ON DELETE SET NULL,
    is_featured boolean NOT NULL DEFAULT false,
    featured_weight integer NOT NULL DEFAULT 0,
    published_at timestamp without time zone,
    last_activity_at timestamp without time zone,
    join_count_total bigint NOT NULL DEFAULT 0,
    join_users_7d bigint NOT NULL DEFAULT 0,
    join_users_30d bigint NOT NULL DEFAULT 0,
    answer_count_7d bigint NOT NULL DEFAULT 0,
    answer_count_30d bigint NOT NULL DEFAULT 0,
    answer_users_7d bigint NOT NULL DEFAULT 0,
    answer_users_30d bigint NOT NULL DEFAULT 0,
    hot_score double precision NOT NULL DEFAULT 0,
    active_score double precision NOT NULL DEFAULT 0,
    recommended_score double precision NOT NULL DEFAULT 0,
    join_mode text NOT NULL DEFAULT 'free',
    join_note text NOT NULL DEFAULT '',
    allow_copy boolean NOT NULL DEFAULT true,
    share_count bigint NOT NULL DEFAULT 0,
    snapshot_generation bigint NOT NULL CHECK (snapshot_generation > 0),
    projection_digest char(64) NOT NULL DEFAULT repeat('0', 64)
        CHECK (projection_digest ~ '^[0-9a-f]{64}$'),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_public_bank_plaza_metric_source UNIQUE (source_type, source_id)
);

CREATE INDEX ix_public_bank_plaza_latest
    ON public_bank_plaza_metrics (published_at DESC, source_id DESC, source_type ASC);
CREATE INDEX ix_public_bank_plaza_hot
    ON public_bank_plaza_metrics (
        hot_score DESC,
        published_at DESC,
        source_id DESC,
        source_type ASC
    );
CREATE INDEX ix_public_bank_plaza_active
    ON public_bank_plaza_metrics (
        active_score DESC,
        last_activity_at DESC,
        source_id DESC,
        source_type ASC
    );
CREATE INDEX ix_public_bank_plaza_featured
    ON public_bank_plaza_metrics (
        is_featured,
        featured_weight DESC,
        recommended_score DESC,
        published_at DESC,
        source_id DESC,
        source_type ASC
    );
CREATE INDEX ix_public_bank_plaza_questions
    ON public_bank_plaza_metrics (
        question_count_total DESC,
        published_at DESC,
        source_id DESC,
        source_type ASC
    );
CREATE INDEX ix_public_bank_plaza_board
    ON public_bank_plaza_metrics (plaza_board_id);
CREATE INDEX ix_public_bank_plaza_snapshot_boundary
    ON public_bank_plaza_metrics (
        snapshot_generation,
        projection_digest,
        source_type,
        source_id
    );

CREATE TABLE public_bank_plaza_viewer_state (
    identity_id bigint NOT NULL,
    source_type text NOT NULL CHECK (source_type IN ('system', 'user_public')),
    source_id bigint NOT NULL,
    has_public boolean NOT NULL DEFAULT false,
    has_shared boolean NOT NULL DEFAULT false,
    last_activity_at timestamp with time zone,
    snapshot_generation bigint NOT NULL CHECK (snapshot_generation > 0),
    projection_digest char(64) NOT NULL DEFAULT repeat('0', 64)
        CHECK (projection_digest ~ '^[0-9a-f]{64}$'),
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_public_bank_plaza_viewer_state
        PRIMARY KEY (identity_id, source_type, source_id),
    CONSTRAINT fk_public_bank_plaza_viewer_metric
        FOREIGN KEY (source_type, source_id)
        REFERENCES public_bank_plaza_metrics (source_type, source_id)
        ON DELETE CASCADE
);

CREATE INDEX ix_public_bank_plaza_viewer_activity
    ON public_bank_plaza_viewer_state (
        last_activity_at,
        source_type,
        source_id,
        identity_id
    );
CREATE INDEX ix_public_bank_plaza_viewer_snapshot_boundary
    ON public_bank_plaza_viewer_state (
        snapshot_generation,
        projection_digest,
        identity_id,
        source_type,
        source_id
    );

CREATE TABLE public_bank_plaza_snapshot_state (
    snapshot_name text PRIMARY KEY CHECK (snapshot_name = 'public-bank-plaza'),
    status text NOT NULL CHECK (status IN ('building', 'complete', 'failed')),
    last_success_at timestamp with time zone,
    metrics_count bigint NOT NULL CHECK (metrics_count >= 0),
    system_count bigint NOT NULL CHECK (system_count >= 0),
    user_public_count bigint NOT NULL CHECK (user_public_count >= 0),
    viewer_state_count bigint NOT NULL CHECK (viewer_state_count >= 0),
    projection_digest char(64) NOT NULL
        CHECK (projection_digest ~ '^[0-9a-f]{64}$'),
    projector_schema_version integer NOT NULL CHECK (projector_schema_version > 0),
    source_high_watermark text NOT NULL CHECK (btrim(source_high_watermark) <> ''),
    generation bigint NOT NULL CHECK (generation > 0),
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_public_bank_snapshot_source_counts
        CHECK (metrics_count = system_count + user_public_count),
    CONSTRAINT ck_public_bank_snapshot_complete_timestamp
        CHECK (status <> 'complete' OR last_success_at IS NOT NULL)
);

CREATE FUNCTION invalidate_public_bank_complete_snapshot()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public_bank_plaza_snapshot_state
       SET status = 'failed',
           updated_at = clock_timestamp()
     WHERE snapshot_name = 'public-bank-plaza'
       AND status = 'complete';
    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_public_bank_metrics_invalidate_snapshot
AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE
ON public_bank_plaza_metrics
FOR EACH STATEMENT
EXECUTE FUNCTION invalidate_public_bank_complete_snapshot();

CREATE TRIGGER trg_public_bank_boards_invalidate_snapshot
AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE
ON plaza_boards
FOR EACH STATEMENT
EXECUTE FUNCTION invalidate_public_bank_complete_snapshot();

CREATE TRIGGER trg_public_bank_viewer_invalidate_snapshot
AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE
ON public_bank_plaza_viewer_state
FOR EACH STATEMENT
EXECUTE FUNCTION invalidate_public_bank_complete_snapshot();
