-- Phase 2 schema-only fixture derived from the observed legacy `subjects` table.
-- It is intentionally minimal and MUST NOT be treated as a Flyway baseline,
-- production migration, or proof of the production PostgreSQL version.

CREATE TABLE plaza_boards (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT plaza_boards_pkey PRIMARY KEY (id)
);

CREATE SEQUENCE subjects_id_seq AS integer;

CREATE TABLE subjects (
    id integer DEFAULT nextval('subjects_id_seq'::regclass) NOT NULL,
    name text NOT NULL,
    description text,
    is_locked boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    plaza_board_id integer,
    is_plaza_featured boolean DEFAULT false NOT NULL,
    plaza_featured_weight integer DEFAULT 0 NOT NULL,
    plaza_featured_at timestamp without time zone,
    CONSTRAINT subjects_pkey PRIMARY KEY (id),
    CONSTRAINT subjects_name_key UNIQUE (name),
    CONSTRAINT fk_subjects_plaza_board_id
        FOREIGN KEY (plaza_board_id) REFERENCES plaza_boards(id) ON DELETE SET NULL
);

ALTER SEQUENCE subjects_id_seq OWNED BY subjects.id;

INSERT INTO plaza_boards (id) VALUES (1);
INSERT INTO subjects (
    name,
    description,
    is_locked,
    plaza_board_id,
    is_plaza_featured,
    plaza_featured_weight,
    plaza_featured_at
) VALUES (
    'Phase 2 reference subject',
    'Schema-only fixture; never a production baseline',
    false,
    1,
    true,
    10,
    TIMESTAMP '2026-07-16 00:00:00'
);
